# -----------------------------------------------------------------------------
# application - this is the name of the application
# -----------------------------------------------------------------------------
application: hw-2-inf-system
# -----------------------------------------
# the version of the application we create
# -----------------------------------------
version: 1
# -----------------------------------------
# programming language
# -----------------------------------------
runtime: python27
# -----------------------------------------
# python sub version
# -----------------------------------------
api_version: 1
# ---------------------------------------------------------------------
# threadsafe - to prevent collision between calls to the application
#              from different clients
# ---------------------------------------------------------------------
threadsafe: true
# ---------------------------------------------------------------------
# handlers - define an application file for each URL we get
# ---------------------------------------------------------------------
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.app
# ---------------------------------------------------------------------
# libraries in use - jinja2(latest version)
# ---------------------------------------------------------------------
libraries:
- name: jinja2
  version: latest
  
  